<!DOCTYPE html>
<html ng-app="WeddingPlacesRecords">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
        <title>Wedding Places Web Api v1.0</title>

        <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="../styles/main.css">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.4/angular.min.js"></script>
        <script src="../js/jquery.min.js"></script>
        <script src="../app/app.js"></script>
        <script src="../app/controllers/weddingplacesrecords.js"></script>
    </head>
    <body>
        <div class="jumbotron">
            <h1 class="display-4">Wedding Places api v1.0</h1>
        </div>

        <div ng-controller="WeddingPlacesController" style="margin: 3px">

            <div class="row">
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="search" name="search" placeholder="Search" ng-model="search" ng-change="toggle('search', '')">
                </div>
                <div class="col-lg-6">
                    <button type="button" class="btn btn-success float-right" ng-click="toggle('refresh', '')">Refresh</button>
                    <button type="button" class="btn btn-primary float-right" ng-click="toggle('new', '')">Add New</button>
                </div>
            </div>



            <div ng-if="screen_type==1">
                <form name="frmPlace">
                    <div class="form-group">
                        <label for="exampleInputEmail1">City</label>
                        <input type="text" class="form-control" id="city" name="city" placeholder="City" ng-model="place.city" ng-required="true">
                        <span class="help-inline btn-danger" ng-show="frmPlace.city.$invalid && frmPlace.city.$touched">Zorunlu alan</span>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Place</label>
                        <input type="text" class="form-control" id="place" name="place" placeholder="Place" ng-model="place.place" ng-required="true">
                        <span class="help-inline btn-danger" ng-show="frmPlace.place.$invalid && frmPlace.place.$touched">Zorunlu alan</span>
                    </div>
                    <button type="button" ng-disabled="frmPlace.$invalid" class="btn btn-primary" ng-click="toggle('save', '')">Save</button>
                    <button type="button" class="btn btn-danger" ng-click="toggle('cancel', '')">Cancel</button>
                </form>
            </div>

            <table class="table table-hover" ng-if="screen_type==0">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">City</th>
                    <th scope="col">Place</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="place in places">
                    <td>{{ place.city }}</td>
                    <td>{{ place.place }}</td>
                    <td>
                        <button type="button" class="btn btn-primary" ng-click="toggle('edit', place)">Edit</button>
                        <button type="button" class="btn btn-danger" ng-click="toggle('delete', place)">Delete</button>
                    </td>
                </tr>
                </tbody>
            </table>

        </div>
    </body>
</html>
